# Generated by Django 4.2.17 on 2026-04-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('ma_tk', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã tài khoản')),
                ('ten_dang_nhap', models.CharField(max_length=150, unique=True, verbose_name='Tên đăng nhập')),
                ('mat_khau', models.CharField(max_length=255, verbose_name='Mật khẩu (hash)')),
                ('ma_phan_quyen', models.IntegerField(choices=[(1, 'Quản lý'), (2, 'Nhân viên')], default=2, verbose_name='Phân quyền')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Tài khoản',
                'verbose_name_plural': 'Tài khoản',
                'db_table': 'tai_khoan',
                'ordering': ['ten_dang_nhap'],
            },
        ),
    ]
