# Generated by Django 4.2.17 on 2026-04-29 14:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('tables', '0001_initial'),
        ('menu', '0001_initial'),
        ('promotions', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('ma_hd', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã hóa đơn')),
                ('ngay_lap', models.DateTimeField(auto_now_add=True, verbose_name='Ngày lập')),
                ('tong_tien', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tổng tiền (VNĐ)')),
                ('phuong_thuc', models.CharField(choices=[('Tiền mặt', 'Tiền mặt'), ('Chuyển khoản', 'Chuyển khoản')], default='Tiền mặt', max_length=20, verbose_name='Phương thức thanh toán')),
                ('trang_thai', models.CharField(choices=[('Chờ pha chế', 'Chờ pha chế'), ('Hoàn tất', 'Hoàn tất'), ('Đã hủy', 'Đã hủy')], default='Chờ pha chế', max_length=20, verbose_name='Trạng thái')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('ma_ban', models.ForeignKey(db_column='ma_ban', on_delete=django.db.models.deletion.PROTECT, related_name='hoa_don', to='tables.ban', verbose_name='Bàn')),
                ('ma_km', models.ForeignKey(blank=True, db_column='ma_km', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoa_don', to='promotions.khuyenmai', verbose_name='Khuyến mãi áp dụng')),
                ('ma_nv', models.ForeignKey(db_column='ma_nv', on_delete=django.db.models.deletion.PROTECT, related_name='hoa_don', to='staff.nhanvien', verbose_name='Nhân viên lập')),
                ('sdt_khach', models.ForeignKey(blank=True, db_column='sdt_khach', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoa_don', to='customers.khachhang', verbose_name='Khách hàng (SDT)')),
            ],
            options={
                'verbose_name': 'Hóa đơn',
                'verbose_name_plural': 'Hóa đơn',
                'db_table': 'hoa_don',
                'ordering': ['-ngay_lap'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng')),
                ('gia_ban', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Giá bán tại thời điểm (VNĐ)')),
                ('ghi_chu', models.CharField(blank=True, default='', max_length=255, verbose_name='Ghi chú')),
                ('ma_hd', models.ForeignKey(db_column='ma_hd', on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='orders.hoadon', verbose_name='Hóa đơn')),
                ('ma_mon', models.ForeignKey(db_column='ma_mon', on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_hoa_don', to='menu.thucdon', verbose_name='Món')),
            ],
            options={
                'verbose_name': 'Chi tiết hóa đơn',
                'verbose_name_plural': 'Chi tiết hóa đơn',
                'db_table': 'chi_tiet_hoa_don',
                'unique_together': {('ma_hd', 'ma_mon')},
            },
        ),
    ]
