# Generated by Django 4.2.17 on 2026-04-29 14:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TonKho',
            fields=[
                ('ma_nl', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã nguyên liệu')),
                ('ten_nl', models.CharField(max_length=150, verbose_name='Tên nguyên liệu')),
                ('so_luong_ton', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Số lượng tồn')),
                ('don_vi_tinh', models.CharField(max_length=30, verbose_name='Đơn vị tính')),
                ('nguong_bao_dong', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ngưỡng báo động')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'verbose_name_plural': 'Tồn kho',
                'db_table': 'ton_kho',
                'ordering': ['ten_nl'],
            },
        ),
        migrations.CreateModel(
            name='PhieuNhap',
            fields=[
                ('ma_phieu', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã phiếu nhập')),
                ('ngay_nhap', models.DateField(verbose_name='Ngày nhập')),
                ('tong_gia_tri', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tổng giá trị (VNĐ)')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('ma_nv', models.ForeignKey(db_column='ma_nv', on_delete=django.db.models.deletion.PROTECT, related_name='phieu_nhap', to='staff.nhanvien', verbose_name='Nhân viên nhập')),
            ],
            options={
                'verbose_name': 'Phiếu nhập',
                'verbose_name_plural': 'Phiếu nhập',
                'db_table': 'phieu_nhap',
                'ordering': ['-ngay_nhap', '-ma_phieu'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhieuNhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_nhap', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Số lượng nhập')),
                ('don_gia_nhap', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đơn giá nhập (VNĐ)')),
                ('ma_nl', models.ForeignKey(db_column='ma_nl', on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_nhap', to='inventory.tonkho', verbose_name='Nguyên liệu')),
                ('ma_phieu', models.ForeignKey(db_column='ma_phieu', on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='inventory.phieunhap', verbose_name='Phiếu nhập')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu nhập',
                'verbose_name_plural': 'Chi tiết phiếu nhập',
                'db_table': 'chi_tiet_phieu_nhap',
                'unique_together': {('ma_phieu', 'ma_nl')},
            },
        ),
    ]
