# Generated by Django 4.2.17 on 2026-04-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('ma_ban', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã bàn')),
                ('ten_khu_vuc', models.CharField(max_length=100, verbose_name='Tên / Khu vực')),
                ('trang_thai', models.IntegerField(choices=[(0, 'Trống'), (1, 'Có khách'), (2, 'Đang dọn')], default=0, verbose_name='Trạng thái')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Bàn',
                'verbose_name_plural': 'Bàn',
                'db_table': 'ban',
                'ordering': ['ten_khu_vuc', 'ma_ban'],
            },
        ),
    ]
