# Generated by Django 4.2.17 on 2026-04-29 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('sdt_khach', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải có từ 9 đến 11 chữ số.', regex='^\\d{9,11}$')], verbose_name='Số điện thoại (PK)')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('diem_tich_luy', models.PositiveIntegerField(default=0, verbose_name='Điểm tích lũy')),
                ('hang_tv', models.CharField(choices=[('Đồng', 'Đồng'), ('Bạc', 'Bạc'), ('Vàng', 'Vàng'), ('Kim cương', 'Kim cương')], default='Đồng', max_length=20, verbose_name='Hạng thành viên')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'db_table': 'khach_hang',
                'ordering': ['ho_ten'],
            },
        ),
    ]
