# Generated by Django 4.2.17 on 2026-04-29 14:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('ma_km', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã khuyến mãi')),
                ('ten_chuong_trinh', models.CharField(max_length=200, verbose_name='Tên chương trình')),
                ('ngay_bd', models.DateField(verbose_name='Ngày bắt đầu')),
                ('ngay_kt', models.DateField(verbose_name='Ngày kết thúc')),
                ('phan_tram_giam', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Phần trăm giảm (%)')),
                ('dieu_kien_toi_thieu', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Điều kiện tối thiểu (VNĐ)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Khuyến mãi',
                'verbose_name_plural': 'Khuyến mãi',
                'db_table': 'khuyen_mai',
                'ordering': ['-ngay_bd'],
            },
        ),
    ]
