# Generated by Django 4.2.17 on 2026-04-29 14:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('ma_nv', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã nhân viên')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('sdt', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải có từ 9 đến 11 chữ số.', regex='^\\d{9,11}$')], verbose_name='Số điện thoại')),
                ('dia_chi', models.TextField(blank=True, default='', verbose_name='Địa chỉ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang làm việc')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('ma_tk', models.OneToOneField(blank=True, db_column='ma_tk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhan_vien', to='authentication.taikhoan', verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'db_table': 'nhan_vien',
                'ordering': ['ho_ten'],
            },
        ),
        migrations.CreateModel(
            name='CaLam',
            fields=[
                ('ma_ca', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã ca')),
                ('ngay_lam', models.DateField(verbose_name='Ngày làm')),
                ('gio_bat_dau', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('gio_ket_thuc', models.TimeField(verbose_name='Giờ kết thúc')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ma_nv', models.ForeignKey(db_column='ma_nv', on_delete=django.db.models.deletion.CASCADE, related_name='ca_lam', to='staff.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Ca làm',
                'verbose_name_plural': 'Ca làm',
                'db_table': 'ca_lam',
                'ordering': ['-ngay_lam', 'gio_bat_dau'],
                'unique_together': {('ma_nv', 'ngay_lam', 'gio_bat_dau')},
            },
        ),
        migrations.CreateModel(
            name='ChamCong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gio_vao_thuc', models.TimeField(blank=True, null=True, verbose_name='Giờ vào thực tế')),
                ('gio_ra_thuc', models.TimeField(blank=True, null=True, verbose_name='Giờ ra thực tế')),
                ('trang_thai', models.CharField(choices=[('Đúng giờ', 'Đúng giờ'), ('Đi trễ', 'Đi trễ'), ('Đi trễ nặng', 'Đi trễ nặng'), ('Chưa chấm', 'Chưa chấm'), ('Vắng', 'Vắng')], default='Chưa chấm', max_length=20, verbose_name='Trạng thái')),
                ('ghi_chu', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('ma_ca', models.ForeignKey(db_column='ma_ca', on_delete=django.db.models.deletion.CASCADE, related_name='cham_cong', to='staff.calam', verbose_name='Ca làm')),
                ('ma_nv', models.ForeignKey(db_column='ma_nv', on_delete=django.db.models.deletion.CASCADE, related_name='cham_cong', to='staff.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Chấm công',
                'verbose_name_plural': 'Chấm công',
                'db_table': 'cham_cong',
                'ordering': ['-ngay_tao'],
                'unique_together': {('ma_ca', 'ma_nv')},
            },
        ),
    ]
