# Generated by Django 4.2.17 on 2026-04-29 14:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThucDon',
            fields=[
                ('ma_mon', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã món')),
                ('ten_mon', models.CharField(max_length=150, verbose_name='Tên món')),
                ('ma_loai', models.CharField(max_length=50, verbose_name='Mã loại / Danh mục')),
                ('don_gia', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đơn giá (VNĐ)')),
                ('mo_ta', models.TextField(blank=True, default='', verbose_name='Mô tả')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Hình ảnh')),
                ('trang_thai', models.IntegerField(choices=[(0, 'Hết'), (1, 'Còn')], default=1, verbose_name='Trạng thái')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Thực đơn',
                'verbose_name_plural': 'Thực đơn',
                'db_table': 'thuc_don',
                'ordering': ['ma_loai', 'ten_mon'],
            },
        ),
    ]
