version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: cafe_db
    environment:
      MYSQL_DATABASE: cafe_management
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: cafe_backend
    command: >
      bash -c "python manage.py migrate --settings=config.settings_dev &&
               python seed.py &&
               gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=cafe_management
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DJANGO_SETTINGS_MODULE=config.settings_dev
    depends_on:
      - db

  pos-app:
    build: ./pos-app
    container_name: cafe_pos
    ports:
      - "5173:80"
    depends_on:
      - backend

  website:
    build: ./website
    container_name: cafe_website
    ports:
      - "5174:80"
    depends_on:
      - backend

volumes:
  mysql_data:
